GregTechCEu/gregicality-legacy

src/main/java/gregicadditions/recipes/GARecipeAddition.java

**Problem:**
There is duplicity in Bone to Bone Meal recipes. Because GTCE adds them now too.
**How solved:**
Removed Gregicality duplicit recipes.
Updated Bone to Bone Meal recipe for Forge Hammer to be aligned with new output amounts.
**Outcome:**
Bone to Bone Meal recipe for Mortar and Pulverizer removes to favor GTCE recipes.
Bone to Bone Meal recipe for Forge Hammer outputs 4 instead of 3.

Removed Bone Meal recipes as GTCE already adds them

---

src/main/java/gregicadditions/recipes/LargeRecipeMap.java
src/main/java/gregicadditions/recipes/crafttweaker/CTLargeRecipeBuilder.java
src/main/java/gregicadditions/recipes/crafttweaker/CTLargeRecipeMap.java

This looked like a bug i might be able to fix. It took around 6 hours to find a solution, but I'm happy with the result. Here's a working script:
`import mods.gtadditions.recipe.LargeRecipeMap;`
`val large_mixer as LargeRecipeMap = LargeRecipeMap.getByName("large_mixer");`
`   large_mixer.recipeBuilder()`
`   .inputs([<minecraft:iron_ingot> * 2, <ore:ingotGold>])`
`   .outputs([<minecraft:dirt> * 2])`
`   .EUt(120).duration(100)`
`   .dupeForSmall()`
`   .buildAndRegister();`

fix dupeForSmall ct bug

---

src/main/java/gregicadditions/recipes/crafttweaker/CTLargeRecipeMap.java

Why? Because removeByOutput needs a RecipeMap. With this cast it works fine.

Add RecipeMap cast to CTLargeRecipeMap

---

src/main/java/gregicadditions/integrations/opencomputers/OpenComputersCommonProxy.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverMTEBatteryTower.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverMTENuclearReactor.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverMTEVoidMiner.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverMultiblockRecipeLogic.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverQubitMultiblockController.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverTEFusionReactor.java
src/main/java/gregicadditions/integrations/opencomputers/driver/multi/DriverTEWorldAccelerator.java
src/main/java/gregicadditions/machines/TileEntityWorldAccelerator.java
src/main/java/gregicadditions/machines/multi/MetaTileEntityBatteryTower.java
src/main/java/gregicadditions/machines/multi/TileEntityFusionReactor.java
src/main/java/gregicadditions/machines/multi/miner/MetaTileEntityVoidMiner.java
src/main/java/gregicadditions/machines/multi/nuclear/MetaTileEntityNuclearReactor.java

Added some APIs about multi-block (worthy ones).
- `BatteryTower` (I/O per tick)
- `NuclearReactor` (coolant and heat)
- `VoidMiner` and `Fusion` (heat)
- `QubitContainer` for multi-blocks
- `Accelerator` (IControllable and interaction)
Small changes to `BatteryTower` have been made to support monitoring the energy per tick. I think this makes sense, especially requirements with GTCE digitization.

OC API Supplement

---

build.gradle
src/main/java/gregicadditions/coremod/GAClassTransformer.java
src/main/java/gregicadditions/coremod/GACoreMod.java
src/main/java/gregicadditions/coremod/hooks/CoreModHooks.java
src/main/java/gregicadditions/coremod/transform/PacketJEIRecipeTransformer.java

This is a very simple coremod, almost no hacking of AE2. 
Feature: fixed an issue with NBT meta items (such as gt tools) that could not be recognized, when using JEI to import a recipe into the crafting terminal.

Supporting GT tools in AE2

---

src/main/java/gregicadditions/GAMaterials.java
src/main/java/gregicadditions/item/GAMetaItem.java
src/main/java/gregicadditions/item/GAMetaItems.java
src/main/java/gregicadditions/recipes/GARecipeAddition.java
src/main/java/gregicadditions/recipes/chain/VariousChains.java

I have transfered the diagrams for the lignite processing, the oil rig, the polyurethane synthesis, including a new crafting recipe for beds, and the Bose-Einstein condensates. There are things to be done, besides the texturing and localisation. The BCE pellets need to be compatible with some multis and there's also the advanced oil rig logic you might be interested in.

Lignite, oil rig, polyurethane and Bose-Einstein

---

src/main/java/gregicadditions/jei/FusionReactor1Info.java
src/main/java/gregicadditions/jei/FusionReactor2Info.java
src/main/java/gregicadditions/jei/FusionReactor3Info.java
src/main/java/gregicadditions/machines/multi/TileEntityFusionReactor.java
src/main/java/gregicadditions/recipes/GARecipeAddition.java
src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java
src/main/java/gregicadditions/recipes/chain/FusionComponents.java

Modified the Fusion Reactors Mk. 1-3 to use Mk 1, Mk 2, and Mk 3 casings and coils respectively. Also updated the JEI previews to reflect this. Changed the recipes for the fusion casings 2 and 3 to reflect the new tearing. Mk 2 uses Rutherfordium, and Mk 3 uses Dubnium. Fusion coil recipes were updated as well, using LuV, ZPM, and UV power in the Assembly Line for the appropriate tier.

Make regular fusion reactors use the matching casing and coil tier

---

src/main/java/gregicadditions/theoneprobe/GATransformerProvider.java
src/main/java/gregicadditions/theoneprobe/TheOneProbeCompatibility.java

This PR updates our TOP info for transformers to be consistent with the new information displayed in GTCE. I felt it was redundant to add new localization keys since they already existed in GTCE's lang files, but this meant that the key would only resolve if the GTCE version is 1.11.1 or greater.
If GTCE 1.11.1+ is loaded:
If a lower version is loaded (1.8 as is in my dev environment):
If you would like me to change this to not require GTCE 1.11.1+, it would be an easy fix, but would just mean redundant lang entries. Personally, I think it is okay that we do not show this information if GTCE does not either.

Transformer TOP Update

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/capabilities/impl/RecipeMapSteamMultiblockController.java
src/main/java/gregicadditions/capabilities/impl/SteamMultiWorkable.java
src/main/java/gregicadditions/jei/GAMultiblockInfoCategory.java
src/main/java/gregicadditions/jei/multi/simple/SteamOvenInfo.java
src/main/java/gregicadditions/machines/GATileEntities.java
src/main/java/gregicadditions/machines/multi/steam/MetaTileEntitySteamGrinder.java
src/main/java/gregicadditions/machines/multi/steam/MetaTileEntitySteamOven.java
src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java
src/main/resources/assets/gtadditions/lang/en_us.lang

**What:**
This PR expands on the newly added Steam Multiblock parent classes, and adds a new multiblock inspired by the Railcraft Steam Oven, the brother to the Steam Grinder in 1.7.10 GT packs.
**How solved:**
The Steam Oven:
It follows convention with the boilers, and lights up the Firebox Casings when active:
I chose to use Firebox Casings for this since I wanted to make it a bit cheaper than the Steam Grinder, as Railcraft's was a 2x2x2 multiblock.
The recipe, which is also a little cheaper than the Steam Grinder, but not much (uses Invar for gears, like the MultiSmelter):
And lastly, the tooltip and JEI preview:
**Outcome:**
Added Steam Oven
**Additional info:**
- I separated the nested `SteamGrinderWorkable` class and added a parameter for the number of items to process. I left it …

Steam Oven

---

src/main/java/gregicadditions/GAMaterials.java
src/main/java/gregicadditions/recipes/GAMachineRecipeRemoval.java
src/main/java/gregicadditions/recipes/GARecipeAddition.java
src/main/java/gregicadditions/recipes/RecipeHandler.java
src/main/resources/assets/gregtech/models/item/tools/bending_cylinder.json
src/main/resources/assets/gregtech/models/item/tools/bending_cylinder_small.json

- Fixes #315:
See https://github.com/Shadows-of-Fire/Shadows-of-Greg/pull/106 for a description of the fix for this issue.
- Fixes #168:
This issue occurred for any Mixer recipe that had an integrated circuit, but there only happen to be two so far. I added a section of code in the Large Mixer recipe builder to iterate over all inputs, and if it finds a circuit, it removes it from the input list. I also had to save that circuit value, and use it instead of the default logic of `total input items/fluids count` to avoid a conflict.
- Fixes #366:
I added a circuit of configuration 1 to the standard Aluminium EBF recipe. The EUt, duration, and blastTemp are all identical.
- Fixes #271:
I added the flag `EXCLUDE_BLOCK_CRAFTING_RECIPES` and added each recipe manually to use 4 instead of 9.
Each …

Fix Some Outstanding Issues

---

build.gradle
src/main/java/gregicadditions/jei/GAMultiblockInfoCategory.java
src/main/java/gregicadditions/jei/LargeMultiblockInfoRecipeWrapper.java

This PR fixes our multiblock previews when GTCE version 1.12.0+ is included. There were some changes to the multiblock page methods that required us to pass in additional parameters.
Included in this PR is an update to the `build.gradle` to update our dependency to GTCE 1.12.0.662

Fix Multiblock Preview Page

---

src/main/java/gregicadditions/ClientProxy.java

As simple as the title. I added a method to `ClientProxy` to listen for a `ItemTooltipEvent` and add the tooltip there if it is a SimpleDust. A random example of one of them with a tooltip:

Fix SimpleDusts missing their tooltips

---

build.gradle

The JCenter maven repository has been confirmed to be [shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) in the near future. This PR simply transitions us from using JCenter to pull from maven repositories to using MavenCentral. Functionality is identical, but will keep our projects from mysteriously breaking in the near future.

Switch to MavenCentral from JCenter

---

src/main/java/gregicadditions/machines/multi/TileEntityProcessingArray.java
src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java
src/main/java/gregicadditions/machines/multi/simple/Tuple.java
src/main/java/gregicadditions/utils/Tuple.java

The `Tuple` class (used currently just for a couple Large Multis) is a useful Object to have, and others can potentially use it to help write more organized code. All this PR does is make it generic, add an `equals()` override, and move it to `/util`

Generify Tuple

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/recipes/GAMachineRecipeRemoval.java
src/main/java/gregicadditions/recipes/GARecipeAddition.java

This PR cleans up MachineRecipeRemoval and fixes a couple issues with removals in the file.
First off, a config option is added to enable logging of recipe removals. This is useful for checking which removals are failing and which are succeeding. This is set to default false, because normal players should not need to worry about this option and it could slow down loading of the game.
Also in the config file, an option was removed to make Fine Wire recipes from Foils, as this does not exist anymore in GTCE.
**Recipe Removal File**
- I removed Lead from the list of soldering Materials, as GTCE does not use Lead for any Soldering recipes, and this list is only used in this file, for recipes that the Lead does not apply to.
- I removed the Rotor recipe removals, as this recipe does not exist …

Cleanup MachineRecipeRemoval

---

src/main/java/gregicadditions/ClientProxy.java
src/main/java/gregicadditions/coremod/GAClassTransformer.java
src/main/java/gregicadditions/coremod/hooks/GregTechCEHooks.java
src/main/java/gregicadditions/coremod/transform/GTUtilityTransformer.java
src/main/java/gregicadditions/fluid/GAMetaFluids.java
src/main/java/gregicadditions/materials/SimpleFluidMaterial.java

Following the PR to GTCE https://github.com/GregTechCE/GregTech/pull/1519, I updated our code to allow for fluid tooltips for Simple Fluids as well.
There are 2 parts to this PR:
- Fluid tooltips on Minecraft Buckets
These had to be handled separately, so I handled them in our `ClientProxy` class.
- Fluid tooltips in JEI and in machines
These will not be implemented with this PR. I know, weird right? Well let me explain. This PR includes a coremod for a method in GTCE, `formulaHook`, which I added in my GTCE PR for their fluid tooltips. Now, since this PR is not yet released, our tooltips will similarly not be there in these cases either. However, as soon as that feature is included in GTCE, it will be included for us.
This coremod does **NOT** depend on the feature being added to GTCE, …

Add Fluid Tooltips

---

src/main/resources/assets/gtadditions/lang/en_us.lang
src/main/resources/assets/gtadditions/lang/ru_ru.lang
src/main/resources/assets/gtadditions/lang/zh_cn.lang

This PR simply fixes the issue where UHV+ Cluster Mills had a bad translation key being used in the lang.
While fixing this for the `ru_ru` localization, I noticed there were a few issues with the lang file, thanks to an Intellij plugin I'm using that provides syntax highlighting. I fixed these issues as well.
Closes #402

Fix Cluster Mill Localization

---

src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java

Fixes a Typo that prevents LV-EV GTCE Polarizers not having their recipes removed, causing duplicate recipes with the Gregicality recipes.

Fix GTCE Polarizer recipes not getting removed

---

src/main/java/gregicadditions/recipes/GARecipeAddition.java

As a result of changes in GTCE for Red Alloy in https://github.com/GregTechCE/GregTech/pull/1492, these three recipes are no longer needed, and are not accurate to how the Alloy is changing in GTCE.

Remove Unneeded Red Alloy Recipes

---

src/main/java/gregicadditions/recipes/RecipeHandler.java

Fixes an issue where wire recipes using Insulation Wire Assembly had bad recipe amounts.
Since Insulation Wire Assembly is expensive, the recipes were trying to follow the pattern:
`wireInsulationAmount = (cableAmount == 1) ? 1 : cableAmount / 2`
to save on resources, but was accidentally not doing this, and changing the cable amount too. It now follows this ternary pattern.
Old:
New (1x):
New (2x):
New (4x):
This is not an inclusive list of the recipes, but they are all fine now, and these screenshots show the pattern.

Fix Insulation Wire Assembly Recipes

---

src/main/resources/assets/gregtech/models/item/metaitems/uranium_saturated_yarn.json

This is a simple PR that adds the missing JSON model for Uranium Saturated Yarn, which previously caused it to show up as a missing texture in-game.

Fix Missing JSON for Uranium Saturated Yarn

---

src/main/java/gregicadditions/machines/multi/TileEntityProcessingArray.java

The Ore Washer's Recipe Map name is "orewasher" where the machine name is "ore_washer". This led to an issue where the PA will not recognize the Ore Washer as a valid machine due to it failing to find its Recipe Map. This PR fixes this.

Fix Ore Washer in PA

---

build.gradle
src/main/java/gregicadditions/Gregicality.java
src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java

This PR does two things:
- Updates our GTCE dependency to 1.13.0, and sets a `required-after:gregtech[1.13.0,)` since many of our chemical chains are going to depend on a new GTCE feature introduced in 1.13.0, https://github.com/GregTechCE/GregTech/pull/1514
- Fixes Large Multis not being able to handle notConsumed fluids due to a divide by 0 exception

Fix NotConsumed Fluids in Large Multis

---

src/main/java/gregicadditions/machines/multi/TileEntityProcessingArray.java

supersedes #426
After the recipe was built it the PA adds the machine in the dedicate slot as an input of the recipe, due to leftover of the old logic when the machine stack worked from inside the bus.
removed adding machine stack to the recipe when setting the machine stack to not consumable.
removed reflection.
removed comparison by string references

fix PA not running due to add the machinestack as recipe input

---

src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeBenderAndForming.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeMultiUse.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargePackager.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeWashingPlant.java

Potentially prevents a race condition on world load causing an NPE. This should fix it.

Remove scheduleRenderUpdate() method calls

---

src/main/java/gregicadditions/recipes/wrapper/GARecipeWrapper.java

This PR mirrors a change made in GTCE to drop NBT for JEI recipes for things like chanced outputs, not consumed inputs, etc in favor of a cached value. See https://github.com/GregTechCE/GregTech/pull/1516 for information.
The primary reason for this (aside from a cleaner implementation not requiring NBT) is because JEI lacks a subtype handler for fluids in 1.12.2. This means that it is unable to differentiate fluids with NBT data. For example,
- Water would have a JEI uid of:
`fluid:water`
- Water, but set as not consumable, with an NBT tag to mark it would have a JEI uid of:
`fluid:water{not_consumed:1b}`
This results in JEI treating Water and "Not Consumable Water" as two different ingredients, leading to recipe lookup failing for not consumable fluids. By dropping NBT, this is a …

Drop NBT From JEI Recipes

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/item/behaviors/ProspectingToolBehaviour.java

Some of the parameters for the ProspectorStats constructor were out of order, leading to the scanCosts field being set to the chunk radius. This would cause the server instance of the world to get stuck trying to scan a chunk radius in the thousands, leading to a hard crash (and sometimes world corruption) on force close.
Additionally, I decreased the scanCosts even further since with default settings, the Prospector still could not be kept open for more than a few seconds from full charge with default settings.
Personally, I think that this highlights an issue of commits being applied directly to master. I think that we should have all code changes (except for the occasional compilation error fix) come through a PR first so that at least trivial typos can be caught by the rest of the …

Fix Prospector Hard Crash

---

src/main/java/gregicadditions/machines/MetaTileEntityDrum.java
src/main/java/gregicadditions/machines/TileEntityBuffer.java
src/main/java/gregicadditions/machines/TileEntityCrate.java

Similar to https://github.com/GregTechCE/GregTech/pull/1481 which is applied to the GTCE chest, this PR applies the same fix to the Gregicality Drum and Crate to prevent untextured/uncolored breaking particles.
Edit: Second commit is to fix Buffers having missing texture breaking particles, pointed out to me by Tech on discord

Fix breaking particles for Drum and Crate

---

src/main/java/gregicadditions/machines/multi/override/MetaTileEntityCrackingUnit.java

This PR decreases the minimum required cracking unit casings to allow for more inputs and outputs on a single multiblock. Currently, you need to use many cracking units to automate a single gas centrifuge for nuclear products, which decentivizes the use of better coils in them. The changed amount allows for 4 fluid inputs and 4 fluid outputs as well as one energy hatch per multiblock at most. This allows all 3 outputs of the gas centrifuge to be processed inside a single multiblock with dedicated filtered output hatches, giving players better means to automating the process in its current state.

Decrease minimum cracking unit casings

---

build.gradle

Removes Tehnut's maven as nothing in the project was depending on it. Required making Ex Nihilo Creatio not transitive so it did not attempt to bring HWYLA with it

Remove the HWYLA maven

---

src/main/java/gregicadditions/capabilities/impl/SteamMultiWorkable.java
src/main/java/gregicadditions/machines/multi/multiblockpart/MetaTileEntitySteamItemBus.java

This PR fixes a crash with Steam Multiblocks when there are no outputs present, only chanced outputs. The largest example of this is with the Steam Grinder, when macerating Poor Ores. Now it has logic to check for if outputs is empty, and simply use the first chanced output in the list (being crushed) to still ignore the HV+ maceration byproducts.
This PR also fixes an issue with the Steam Item Input/Output buses, using the wrong overlay texture.

Fix Steam Multi Crash

---

src/main/java/gregicadditions/theoneprobe/GADiodeProvider.java
src/main/java/gregicadditions/theoneprobe/GATransformerProvider.java
src/main/resources/assets/gtadditions/lang/en_us.lang

This PR fixes an issue where the translation keys are not properly translated in TOP for the Diodes and Transformers. End result is no visible change, except that the text will display properly in TOP when the world is hosted on a server.

Fix Some Translation Issues in TOP

---

src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeChemicalReactor.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeMultiUse.java

This PR allows for multiblocks that extend `LargeSimpleRecipeMapMultiblockController` to disable the Distinct Buses feature entirely. This was done for:
- The LCR, since it really doesn't make sense for that machine
- The Multi-Use, since it has some issues with the feature causing crashes, so it will be disabled for now for the 0.22 release until a better fix is found

Add Disable to Distinct Buses Mode

---

src/main/java/gregicadditions/CommonProxy.java

This PR simply adds a mechanism for applying a "to be removed" tooltip to materials we will be removing in future releases.
This is useful when we want to remove a material, but do not want to just delete the material from all player's worlds. This tooltip will make it clear to the player that the material can no longer be produced and should be used up before the release following.
This applies to items and fluids, though currently we are only doing it for 1 fluid material. For Simple Materials, we can just apply the tooltip to the material itself since it accepts a String tooltip, but GTCE materials do not so it has to be done this way.

Add Tooltip Override for Removed Materials

---

src/main/java/gregicadditions/recipes/OreRecipeHandler.java

This PR changes Poor Ores to no longer use chanced outputs on the crushed output. Currently, Poor Ores are next to useless as a result of the chanced nature, and are better furnace smelted than processed any further. This PR addresses this by changing the output type to a regular output.

Buff Poor Ores

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/recipes/GARecipeAddition.java

Make superconductor recipes easier. At IV and below superconductors are created in Chemical Bath with Nitrogen.
At LuV and above they're made in the assembler like previously. However, the output now scales with the tier of pump/pipe used. For every tier you can use down to tier - 4 pump and pipe. The input/output amount is 8/16/32/64/128 depending on the tier of pump.

Superconductor recipe buff

---

src/main/java/gregicadditions/integrations/crafttweaker/CTUtils.java

This PR very simply allows for an `@Optional String` to be passed in the `registerFluid` CTUtils method, so that modpack makers can utilize our Fluid Tooltip system when adding new Simple Fluids. Since it is marked as `optional`, it will not break any existing scripts, and modpack authors simply have to add a String after the name and rgb values where they make fluids already.

Add Tooltip Ability to Simple Fluids in CT

---

src/main/java/gregicadditions/machines/TileEntitySteamMixer.java

Add an item export handler to the steam mixer's tile entity, as well as the appropriate UI widget. This change is intended for modpack development; it should not break the progression of stock GTCE+Gregicality, and a steam-specific recipe map should not be necessary.

Enable steam mixer to output items

---

build.gradle.kts
build.properties

This PR removes ForgeMultiPart as a dependency from our project completely. We are not using it at all, and GTCE was using it for legacy support for versions older than August 2019. GTCE removed the dependency here: https://github.com/GregTechCE/GregTech/pull/1594, so we may as well do the same.

Remove ForgeMultiPart Dependency

---

src/main/java/gregicadditions/GAMaterials.java
src/main/java/gregicadditions/recipes/categories/RecipeOverride.java

I made a few small changes to balance the platinum group process a little better, mostly adapted from Bartworks.
- Sheldonite Ore no longer smelts into Platinum Ingots, it no longer has direct Platinum and Iridium byproducts, and no longer electrolyzes to Platinum and Iridium. Instead, these have been replaced with Platinum Metallic Powder and Iridium Leach in all cases, and had their output amounts doubled. This is consistent with Bartworks' implementation, as this ore was very overpowered and game breaking. If an ore like this is desired, there is still Platinum Ore, Iridium Ore, etc..
- I re-enabled Platinum Group Sludge from GTCE. I updated it similarly to how it is handled by Bartworks, and now instead have it output the various Platgroup starting points, and double their outputs. …

Fix some loose ends with PlatLine

---

build.properties
src/main/java/gregicadditions/Gregicality.java
src/main/java/gregicadditions/item/behaviors/monitorPlugin/FakeGuiPluginBehavior.java
src/main/java/gregicadditions/recipes/compat/jei/GARecipeMapCategory.java
src/main/java/gregicadditions/recipes/compat/jei/GARecipeWrapper.java
src/main/java/gregicadditions/recipes/impl/LargeRecipeBuilder.java
src/main/java/gregicadditions/widgets/WidgetOreList.java

The update to GTCE 1.15.0 introduced a number of breaking changes, first being https://github.com/GregTechCE/GregTech/pull/1485 which required some updates to our Widget use.
- I updated the `FakeGuiPluginBehavior` class code that was checking for if a Slot belonged to a player inventory. This part needs to be tested as I did not know how to test it, but I am confident it will work
- I updated `GARecipeMapCategory` which simply needed to reorganize its checks a bit. This code was updated identically to similar code in GTCE
- I updated `WidgetOreList` code which was updating the ItemStack in a Slot. Based on testing with the Prospector, I believe this all works perfectly but since I did not write this code, I'm not certain I tested the change. However I am again confident that it is good …

Update to GTCE 1.15.0

---

src/main/java/gregicadditions/integrations/tconstruct/FluidTemp.java

A quick fix for this tinkers warning seen in the log, 
```less
[12:59:10] [Client thread/ERROR]: Failed to load material handler class gregicadditions.integrations.tconstruct.FluidTemp from Gregicality-1.12.2-0.22.3.1.jar: class does not implement IMaterialHandler
[12:59:10] [Client thread/ERROR]: Consult the mod author for fix on his side.
```
This fix is basically just copying what was done here, <https://github.com/Shadows-of-Fire/Shadows-of-Greg/commit/f40d47768b4f5e9d55fc8bd0b9526444df030a05>

Quick fix for Tinkers warning

---

src/main/java/gregicadditions/recipes/categories/circuits/CircuitRecipes.java

This PR does 2 things:
- Fixes the issue with circuits taking far more Soldering Alloy than they should. It is now back to previous behavior.
- Re-enables SoC recipes for circuits Refined through Wetware. We may want to look into SoC recipes for later tier circuits as well, but for now I think this is a helpful addition

Fix Some Circuit Issues

---

src/main/java/gregicadditions/item/GAMetaItem.java
src/main/java/gregicadditions/recipes/categories/RecipeOverride.java

This PR re-enables the Compressed Clay recipes and unhides it from JEI. This allows bricks to be craftable again before an Alloy Smelter.

Fix bricks being uncraftable early game

---

src/main/java/gregicadditions/recipes/categories/RecipeOverride.java

This PR simply adds 2 new recipes for making Glass, from GT5:
- Forming Press: Glass Dust + Block Mold (not consumed) -> Glass
- Arc Furnace: Sand + some oxygen -> 2 Glass

Add a couple more ways to make Glass from GT5

---

src/main/java/gregicadditions/recipes/GARecipeMaps.java
src/main/java/gregicadditions/recipes/categories/CasingRecipes.java
src/main/java/gregicadditions/recipes/categories/handlers/NuclearHandler.java

This PR addresses the massive loss in fluorine resulting from the Nuclear Process. 
First, this PR fixes the remaining chemistry problems within the NuclearHandler, except for one recipe which would require extra item inputs and would cause significant problems for existing setups. The Nitrite materials are also actually supposed to be Nitrates, and the chemistry reflects this. Durations and EUts have been made static for all inputs, allowing automation of the process to be more standardized. The durations have also been reduced.
The Gas Centrifuge is the cause of the fluorine loss, and could also lead to positive fluorine loops. This PR changes the gas centrifuge to only have one recipe per nuclear input fluid, which is equivalent to the old ULV-tier recipe. This recipe uses 2A of HV …

Fix Nuclear Fluorine

---

src/main/java/gregicadditions/covers/CoverDigitalInterface.java

One of my friend pointed out that when using the mulktiblock battery the number showed by the digital interface may  overflow from where it should be:
i fixed this by changing a little the computation in order to make easier to add new  unit tier (yeah not sure about how to says this) and adding the Giga Terra and Peta prefix hopping it should be enough

updated digital interface to support larger amount of item/fluid/energy

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/GAMaterials.java
src/main/java/gregicadditions/item/GAMetaItem.java
src/main/java/gregicadditions/recipes/RecipeHandler.java
src/main/java/gregicadditions/recipes/categories/RecipeOverride.java
src/main/java/gregicadditions/recipes/categories/circuits/CircuitRecipes.java
src/main/java/gregicadditions/recipes/categories/handlers/OreRecipeHandler.java
src/main/java/gregicadditions/recipes/categories/machines/MachineCraftingRecipes.java
src/main/java/gregicadditions/recipes/impl/QubitConsumerRecipeBuilder.java
src/main/resources/assets/gtadditions/lang/en_us.lang

This PR addresses a few issues with recipes, some left over from past PRs, and others older issues:
- Add Assembler Recipes for Drums and Crates including Wood, as they require tools to craft
- Add crushed -> crushedPurified recipes to the Simple Ore Washer
- Fix Schematics decomposing to Stainless Steel, despite being crafted with Steel
- Add a config for harder manual Small Gear recipes instead of forcing it, supersedes #522
- Add 2 <material> -> 1 Small Gear to alloy smelter, for LV Small Gear automation
- Fix Dense Plates, Foils, Double Plates, and Curved Plates using improper recipe durations
- Add Direct Smelting to Iron for Basaltic and Granitic Mineral Sand
- Fix Red Slurry tooltip displaying Silicon despite not containing it
- Add Integrated Circuits to Soldering Alloy, Tin …

More Recipe Fixes

---

src/main/java/gregicadditions/recipes/categories/handlers/DisassemblyHandler.java

Fixes an issue with some unknown combination of mods where some disassembly outputs could wrongly be turned into circuits.
Before (using modpack [Cosmic Chaos](https://www.curseforge.com/minecraft/modpacks/cosmic-chaos) 0.0.05):
After (using Cosmic Chaos 0.0.05 with a custom jar with the fix):

fix: issue with disassembly recipe autogen

---

src/main/java/gregicadditions/GAEnums.java
src/main/java/gregicadditions/Gregicality.java

This PR adds a (kind of terrible, but functional) way of adding new slots to GTCE RecipeMaps. Currently, I have it adding:
- 1 item output to Distillery
- 1 fluid output to Chemical Bath
- +1 item output to Chemical Reactor

Add mechanism to add more slots to GTCE RecipeMaps

---

.github/workflows/checks.yml
src/main/java/gregicadditions/client/LangOverride.java
src/main/resources/assets/gregicality_at.cfg

Fixes a crash some were having with the new LangOverride system introduced in #531. It uses reflection now instead of an access transformer, which is safer overall. Additionally, if it still fails after this fix, it will catch the exception and simply not let the lang override work instead of crashing.

reflect languagemap instead of access transform

---

src/main/java/gregicadditions/integrations/bees/ForestryCommonProxy.java

Fixes seed oil recipes being removed for Wheat Seeds, Pumpkin Seeds, and Melon Seeds if the config option for generating Fluid Extractor recipes from Forestry Squeezer recipes was set to true.
Closes #501

Fix seed oil recipes being removed

---

src/main/java/gregicadditions/recipes/helper/HelperMethods.java

Fixes recipes for multi-amp energy input and output hatches. Closes #517 
The error came about because the recipes for the multi-amp hatches are 1x3 shaped, and so only took up one line in the recipe object. Therefore the start at 3 (Which is fine for a normal 3x3 recipe) would leave some CraftingComponents not transformed into their respective items.

Fix Recipes for Multi-amp inputs and outputs

---

src/main/java/gregicadditions/recipes/categories/handlers/ElectricImplosionHandler.java

Update the Electric Implosion Compressor after the release of the newest GTCE version, which transitioned the Implosion Compressor over to the new property system.
The try/catch was removed because the explosive was transitioned to an itemstack, and the TNT would be the correct itemstack if a custom explosive was not specified.

Update Electric Implosion Compressor

---

src/main/java/gregicadditions/recipes/categories/machines/SingleblockCraftingRecipes.java

Adjusts the 1A transformer recipes to use 1x cables, to prevent recipe conflicts with the higher amperage transformers.
Closes #560

Adjust 1A transformer recipes

---

src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java

This aims to address the issue brought up in #571 by adding an invalidation to the `lastRecipeIndex` when the multiblock structure deforms.
Closes #571

Add caching invalidation on multiblock deform

---

src/main/java/gregicadditions/Gregicality.java

This PR just ensures that when CEu releases, that 0.x releases of Gregicality will display that the mods are incompatible instead of crashing and burning on an error

Add version requirement to block 2.0

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/recipes/categories/ComponentRecipes.java

What: Removes the cheaper assembler component recipes and corresponding config
Outcome: Resolves the conflicts with the component recipes added by GTCE
Possible compatibility issue: May possibly break players setups

remove the cheaper assembler component recipes and config

---

src/main/java/gregicadditions/recipes/chain/UltimateMaterials.java

This PR fixes a small bug that dysprosium is missing in the recipe of periodicium, but in the formula of periodicium.

Add dysprosium into the recipe of periodicium

---

src/main/java/gregicadditions/GAConfig.java
src/main/java/gregicadditions/jei/JEIGAPlugin.java

Adds a config option to hide Poor, Rich, and Pure ores.
This is slightly annoying because there is a config option that generates these ore types outside of their defined orePrefixes, and so lookup by orePrefixes cannot be relied upon if this config is enabled.
Will take a better way to do this

Add config option to hide Poor, Rich, Pure ores

---

src/main/java/gregicadditions/capabilities/impl/GARecipeMapMultiblockController.java

This PR fixes the total time on for multiblock maintenance not being reset after a problem occurs. This would previously cause the multiblock to constantly have problems after the first one arises, and has now been fixed.
This fix is already present in CEu, and was taken from there.

Fix Maintenance Total Time Not Resetting

---

src/main/java/gregicadditions/recipes/categories/machines/MultiblockCraftingRecipes.java

The check for high tier benders being enabled for the large bender recipe was incorrect. This PR fixes it.

fix crash when HT benders are off

---

src/main/java/gregicadditions/recipes/categories/RecipeOverride.java
src/main/java/gregicadditions/recipes/chain/HNIWChain.java

This PR fixes a recipe conflict involving isoprene and oxygen. Isoprene and oxygen in a chemical reactor will currently make raw rubber pulp when attempting to produce Citral instead, preventing progression when working on Bioware circuits.
It also fixes an incorrect recipe for Hexamethylenetetramine where Ammonia was set as an output instead of an input, which created a conflict with any recipe using Formaldehyde as an input as a result. This is also fixed.

Fix Recipe Conflicts

---

src/main/java/gregicadditions/machines/multi/miner/MetaTileEntityChunkMiner.java
src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java

A few fixes for single block miners. Now they:
- Work properly when placed between -1 and -16 on x or z axes (they would reset every time they ended up on a block with x=0 or z=0)
- Stop working and draining energy and lube when done mining instead of starting over
- Reset invalid mining positions that aren't just 2147483647
- Output items even when not powered to match other machines

Miner fixes

---

src/main/java/gregicadditions/recipes/impl/nuclear/HotCoolantRecipe.java

How:
Change the method to reflect the constructor of the hot coolant turbine instead of the standard FuelRecipe constructor.
Outcome: 
Recipes can be added to the hot coolant turbine via CT.
Possible compatibility issue:
None

Fix The CT Constructor for Hot Coolant Turbine Recipes

---

src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeLaserEngraver.java

Fixes the Large Laser Engraver not being able to use fluid hatches. This previously would have prevented the use of key progression recipes, such as making Fullerenes.

Allow Large Engraver to Use Fluid Hatches

---

src/main/java/gregicadditions/recipes/categories/RecipeOverride.java

Fixes a recipe conflict between Vanadium and Sodium Metavanadate in the EBF.

Fix Vanadium and Sodium Metavanadate Conflict

---

src/main/java/gregicadditions/recipes/categories/RecipeOverride.java
src/main/java/gregicadditions/recipes/chain/PEEKChain.java

GSE 6.4 on Gregicality-1.12.2-0.23.3
I think this image explains it succinctly. Resorcinol and Hydroquinone are only craftable by LCR, for which there exists the phenol recipe which overrides with benzene and oxygen inputs. I added a configured circuit to the recipe. Resorcinol is used for the aerographene and PEEK crafting chains.
First pull request to a public repo I hope I did it right~ I tried compiling it to test it but I got the below error on the jar output when running it in forge and I don't know enough about compiling mods to know what the issue is... I would appreciate help with that. I imported in intellij, ran the "jar" target in gradle and used the jar from /build/libs.
```
java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getNamespace()Ljava/lang/String;
at …
```

Fix Resorcinol+Hydroquinone recipe conflict with Phenol in LCR

---

src/main/java/gregicadditions/machines/multi/nuclear/MetaTileEntityGasCentrifuge.java

Now that bonus yield recipes have been removed, I believe this multiblock should be allowed to overclock.

Allow Gas Centrifuge to overclock

---

src/main/java/gregicadditions/GAConfig.java

Blacklists the production of Triniite from the Void Miner Mk1. This would previously cause a progression skip, as Trinium is intended to be gated behind the second miner.

blacklist triniite from void miner mk1

---

src/main/java/gregicadditions/machines/multi/override/MetaTileEntityElectricBlastFurnace.java

Fixes EBF maintenance always adding the non-overclocked duration to the timer. This originally caused overclocked EBFs to have maintenance problems far too quickly because they were adding very long durations in a very short amount of time.

fix ebf maintenance happening too often

---

src/main/java/gregicadditions/recipes/categories/handlers/NuclearHandler.java

What:
Buffs spent fuel repossessing
How:
I lowered the EU/t and duration of fuel reprocessing recipes as they are currently the largest bottleneck of nuclear.
increased the waste created when turning spent fuel nitrate solution(into spent fuel nitride by one. made the fluids and ferrite dust that would normally be looped through red oil not consumed to further increase parallelization of these recipes.

Nuclear reprocessing changes

---

src/main/java/gregicadditions/machines/multi/advance/MetaTileEntityAdvancedDistillationTower.java
src/main/java/gregicadditions/machines/multi/mega/MegaMultiblockRecipeMapController.java
src/main/java/gregicadditions/machines/multi/mega/MetaTileEntityMegaBlastFurnace.java
src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java
src/main/java/gregicadditions/machines/multi/simple/MultiRecipeMapMultiblockController.java
src/main/java/gregicadditions/machines/multi/simple/TileEntityLargeForgeHammer.java

This PR fixes two significant bugs with multiblock logic.
Fixes a voiding bug which occurs with chanced outputs. If a recipe's parallel outputs can fit in the outputs, but not its parallel chanced outputs, the multiblock would previously run the recipe regardless, and void the entire recipe. This PR prevents this by checking if there is enough room to fit all the regular and chanced outputs combined together.
Fixes a bug where multiblocks will lock up if a parallel recipe cannot fit all of its item outputs. Previously, the only way to fix this was to make changes to the input inventory, which is not possible with automation other than laggy setups to unform and reform the structure. Buses were never checked again if the recipe could not fit. This is resolved by returning the non-parallel …

fix multiblock recipe logic bugs

---

src/main/java/gregicadditions/machines/multi/GABoostableWorkableHandler.java
src/main/java/gregicadditions/machines/multi/advance/hyper/MetaTileEntityHyperReactorI.java
src/main/java/gregicadditions/machines/multi/advance/hyper/MetaTileEntityHyperReactorII.java
src/main/java/gregicadditions/machines/multi/advance/hyper/MetaTileEntityHyperReactorIII.java

Fixes Hyper Reactors 2 and 3 extending the wrong class. This meant that they did not require maintenance hatches, and did not boost their output.

Fix Some Generators

---

src/main/java/gregicadditions/machines/multi/miner/MetaTileEntityVoidMiner.java

Small fix for void miner.
problem:
The void miner was constantly cooling down due to asymmetric heating and cooling with the same amount of liquids. Without explicit type casting, an inaccuracy occurred: the cooling was 1 degree more than the heating. And 1 / 1.02 not equal 1 * 0.98.

Void miner stable work fix

---

src/main/java/gregicadditions/recipes/categories/machines/MultiblockCraftingRecipes.java
src/main/java/gregicadditions/recipes/chain/NaquadahChain.java

Changes the isotope used in the large naq reactor recipe to one later in the fission chain. This more closely follows the singleblock naq reactor isotope tearing.
Also changes the isotope used in hyper fuel 3. The new isotope has a higher yield, but requires more infrastructure to reach.

changes to hyper 3 and large naq reactor recipes

---

src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
src/main/java/gregicadditions/machines/multi/simple/LargeSimpleRecipeMapMultiblockController.java

If a not consumable was first in the input list, multiblocks would force max parallel. Fixes this.
Minecraft is really really dumb.

Fix not consumables and parallel
