- src/main/java/gregicadditions/GAConfig.java
- src/main/java/gregicadditions/recipes/RecipeHandler.java
And remove unused config options.
> Add config option to disable new ore processing recipes.

- src/main/java/gregicadditions/GAConfig.java
- src/main/java/gregicadditions/Gregicality.java
Fix bug making config unopenable ingame
> Add config option to disable Mystical Agriculture integration

- src/main/java/gregicadditions/GAConfig.java
- src/main/java/gregicadditions/machines/multi/advance/TileEntityCryogenicFreezer.java
- src/main/java/gregicadditions/machines/multi/advance/TileEntityVolcanus.java
> Fix recipe bug with Volcanus and Cryogenic Freezer

- src/main/resources/mcmod.info
> Give Bart the double quotes he deserves

- src/main/resources/assets/gtadditions/lang/zh_cn.lang
Without strict inspection, there may be mistakes, you can merge first, and then we will check for mistakes later.
> Update the lang file of Chinese Simplified

- src/main/java/gregicadditions/GAConfig.java
- src/main/java/gregicadditions/machines/GATileEntities.java
Fix gas turbine efficieny config option
> Naqudah reactor efficieny config

- src/main/java/gregicadditions/recipes/crafttweaker/CTLargeRecipeMap.java
- src/main/resources/assets/gtadditions/lang/en_us.lang
[test.txt](https://github.com/Gregicality/gregicality/files/5600612/test.txt)
Forgot some machine naming
added a of() method so you can get CTLargeRecipeMap without getByName
and implemented other methods for recipe map like findRecipe()
I atached a script that explains some stuff
> updates for stuff I did

- src/main/java/gregicadditions/coremod/hooks/AppliedEnergistics2Hooks.java
- src/main/java/gregicadditions/coremod/hooks/RefinedStorageHooks.java
- src/main/java/gregicadditions/coremod/transform/NetworkNodeGridTransformer.java
- src/main/java/gregicadditions/coremod/transform/PacketJEIRecipeTransformer.java
- src/main/java/gregicadditions/integrations/bees/GTCombItem.java
- src/main/java/gregicadditions/integrations/bees/alveary/TileGTAlveary.java
- src/main/java/gregicadditions/integrations/bees/effects/GTBeesEffects.java
- src/main/java/gregicadditions/integrations/bees/mutation/MutationConditionFluid.java
- src/main/java/gregicadditions/integrations/bees/mutation/MutationConditionMetaValueItem.java
[crash-report-server](https://discord.com/channels/701354865217110096/779631111256408086/791461241163350056)
Sorry that the mod crashed on the server due to my negligence.
I fixed it,  and double checked the server runnable this time.
> fixes I18n and maybe other bugs

- src/main/java/gregicadditions/GAMaterials.java
- src/main/java/gregicadditions/item/GAMetaItem.java
- src/main/java/gregicadditions/item/GAMetaItems.java
- src/main/java/gregicadditions/recipes/chain/LithiumChain.java
- src/main/java/gregicadditions/recipes/chain/NanotubeChain.java
- src/main/java/gregicadditions/recipes/chain/REEChain.java
- src/main/java/gregicadditions/recipes/chain/SuperconductorsSMDChain.java
- src/main/java/gregicadditions/recipes/chain/VariousChains.java
Superconductors for UHV, UEV and UIV tiers, some materials for smd and sensors and Halide lamps
> Superconductors, SMD materials and Halide Lamps

- src/main/resources/assets/gtadditions/lang/zh_cn.lang
* new cell textures
* LUV -> LuV
* Update zh_cn.lang
* key fix
* Update zh_cn.lang
* newlines
* new lines
* new stuff
* new stuff
* Update zh_cn.lang
* Update zh_cn.lang
* new stuff
* new stuff
* Update zh_cn.lang
* Update en_us.lang
* fix
* Revert "fix"
This reverts commit c4563f4188a6045450e111bb1fd36e0ea795ddeb.
* fix
* New stuff and fixes
* new stuff and fixes
* Update zh_cn.lang
* adds & fixes
* fix
* lil fix
* fix
* Update zh_cn.lang
* new stuff & fixes
* Update zh_cn.lang
> Update zh_cn.lang (#299)

- src/main/java/gregicadditions/GAMaterials.java
- src/main/java/gregicadditions/item/GAMetaItem.java
- src/main/java/gregicadditions/item/GAMetaItems.java
- src/main/java/gregicadditions/item/GASimpleBlock.java
- src/main/java/gregicadditions/recipes/GARecipeAddition.java
- src/main/java/gregicadditions/recipes/GARecipeMaps.java
- src/main/java/gregicadditions/recipes/chain/WormholeGeneratorChain.java
- src/main/resources/assets/gtadditions/lang/en_us.lang
> added wormhole chain

- src/main/java/gregicadditions/item/GAMetaItem.java
- src/main/java/gregicadditions/machines/multi/centralmonitor/MetaTileEntityMonitorScreen.java
discord: [issue](https://discord.com/channels/701354865217110096/792756247689822239/814388605484400662)
> fix recipes

- src/main/java/gregicadditions/GAMaterials.java
- src/main/java/gregicadditions/recipes/RecipeHandler.java
- src/main/java/gregicadditions/recipes/chain/UltimateMaterials.java
- src/main/java/gregicadditions/recipes/chain/VariousChains.java
Simple PR, just to make wire assembly cables useful. If you want to tweak the ratios, feel free to suggest.
> Adding Insulation Wire Assembly to cables

- src/main/java/gregicadditions/machines/multi/TileEntityProcessingArray.java
- src/main/java/gregicadditions/machines/multi/centralmonitor/MetaTileEntityCentralMonitor.java
- src/main/java/gregicadditions/machines/multi/centralmonitor/MetaTileEntityMonitorScreen.java
- Closes #396 
- Fixes compilation issue in `TileEntityProcessingArray`
> Fix compilation issues

- src/main/java/gregicadditions/jei/JEIGAPlugin.java
A very simple PR that can be described by two pictures:
OLD:
NEW:
> Fix Duplicate Furnace Catalysts in JEI

- src/main/java/gregicadditions/machines/multi/MetaTileEntityDrillingRig.java
- src/main/java/gregicadditions/recipes/wrapper/GADrillingRigCategory.java
- src/main/java/gregicadditions/recipes/wrapper/GADrillingRigRecipeWrapper.java
- src/main/resources/assets/gtadditions/lang/en_us.lang
This will make the jei info much more user friendly
I also improved the drilling rig logic.
It will now stop when the output hatches are full (before it would still consume drilling mud energy)
Here is the old jei page
Here is my new jei page
> Drilling rig improvement

- src/main/java/gregicadditions/CommonProxy.java
- src/main/java/gregicadditions/jei/GAMultiblockInfoCategory.java
- src/main/java/gregicadditions/jei/multi/ElectricImplosionInfo.java
- src/main/java/gregicadditions/machines/GATileEntities.java
- src/main/java/gregicadditions/machines/multi/MetaTileEntityElectricImplosion.java
- src/main/java/gregicadditions/recipes/ElectricImplosionHandler.java
- src/main/java/gregicadditions/recipes/GARecipeMaps.java
- src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java
- src/main/resources/assets/gtadditions/lang/en_us.lang
Adapted from Bartworks, the **Electric Implosion Compressor** is a multiblock that serves the same purpose as the Implosion Compressor, but is significantly faster and does not use any form of explosives in its recipes.
In BW, the Electric Implosion Compressor was a 3x9x3 multiblock, taking a whopping 34 Blocks of Neutronium to craft and form. In my implementation, the Neutronium is swapped to Americium, since it is still relatively hard to get, but not nearly as difficult. Additionally, I made the machine only 3x5x3, and trimmed out some unnecessary parts in the multiblock structure.
This multi was UEV-tier in BW. I changed this to UHV for us, to make it a little easier to use, since it is not nearly as important in Gregicality as in GT5. I also cheapened the recipe to craft the …
> Electric Implosion Compressor

- build.gradle
- src/main/java/gregicadditions/covers/CoverDigitalInterface.java
- src/main/java/gregicadditions/machines/multi/centralmonitor/MetaTileEntityCentralMonitor.java
CR: [pastebin](https://pastebin.com/yyrtL1xn)
ISSUE: [discord](https://discord.com/channels/701354865217110096/704380911206006855/829077066023960598)
> [hotFIX] conflict with gtce1.14.0+

- src/main/java/gregicadditions/machines/multi/MetaTileEntityDrillingRig.java
this will fix the drilling rig behaviour produced in #431
> Drilling rig fix

- .gitignore
- build.gradle
- src/main/java/gregicadditions/materials/SimpleDustMaterial.java
- src/main/resources/assets/gregicality_at.cfg
- src/test/java/gtadditions/MaterialIdTest.java
This PR simply adds some testing code to run ID conflict tests on pull requests and on the master branch.
There are certainly many more things that we could (and probably should) test PRs for, if anyone has any ideas, please feel free to suggest them and I can create tests for them.
> Add ID conflict testing to GHA

- src/main/java/gregicadditions/recipes/wrapper/GARecipeWrapper.java
See https://github.com/GregTechCE/GregTech/pull/1576 for explanation
> Fix tooltips on wrong ingredients

- src/main/java/gregicadditions/coremod/GAClassTransformer.java
- src/main/java/gregicadditions/coremod/hooks/GregTechCEHooks.java
- src/main/java/gregicadditions/coremod/transform/CoverPlaceBehaviorTransformer.java
- src/main/java/gregicadditions/coremod/transform/EnergyContainerBatteryBufferTransformer.java
- src/main/java/gregicadditions/coremod/transform/EnergyContainerHandlerTransformer.java
- src/main/java/gregicadditions/coremod/transform/MetaTileEntityTransformer.java
- src/main/java/gregicadditions/coremod/transform/MultiblockControllerBaseTransformer.java
- src/main/java/gregicadditions/coremod/transform/NetworkNodeGridTransformer.java
- src/main/java/gregicadditions/coremod/transform/PacketJEIRecipeTransformer.java
- src/main/java/gregicadditions/coremod/transform/TileEntityControllerTransformer.java
Well, I'm back to the original one. Hopefully I'll find a better way in the future, but for now it should work well for build and release.
> [FIX] coremod fixes

- src/main/java/gregicadditions/item/components/EmitterCasing.java
- src/main/java/gregicadditions/item/components/ReTexturedCasing.java
- src/main/resources/assets/gtadditions/models/block/casing/piston.json
1. Electric Piston blocks have strange textures in the inventory
2. The emitter casing has an incorrect name
3. [discord](https://discord.com/channels/701354865217110096/704380911206006855/838134136417288193)
> [FIX] model-hotfix-0.22

- src/main/java/gregicadditions/recipes/RecipeHandler.java
- src/main/java/gregicadditions/recipes/helper/GACraftingComponents.java
Add a fallback for Lens recipe and changes wires used in IV+ electromagnetic machines
It allows for the crafting of nether star lenses and ZPM+ electromagnetic machines
> Misc crafting fixes

- src/main/java/gregicadditions/recipes/categories/handlers/WireRecipeHandler.java
I mimicked the SoG bundler, but in the Packer. This is intended to work with #508
> Wire bundling in Packer

- .github/workflows/checks.yml
- src/main/java/gregicadditions/GAUtility.java
This PR adds a Linter GHA test to ensure good code quality going forward. It will not error on pre-existing, poorly formatted code, but it will stop any more bad code from going in. There are certainly a few settings with it that will need to be tweaked to be a bit less aggressive, but I think this is a good step towards better code overall.
Eventually I would like to add a gradle task to lint over your changes, so that contributors do not need to open a PR and hope for the best, and can instead lint their code before submitting. However this will probably require first linting over the entire codebase to make it consistent, which will be a large and disruptive PR that should happen when there are no large in-progress PRs.
> Add linter tests to CI

- src/main/resources/assets/gregtech/worldgen/end/naquadah_vein2.json
- src/main/resources/assets/gregtech/worldgen/end/platinum_vein2.json
- src/main/resources/assets/gregtech/worldgen/end/tungstate_vein2.json
- src/main/resources/assets/gregtech/worldgen/nether/magnetite_vein2.json
- src/main/resources/assets/gregtech/worldgen/nether/precious_vein.json
- src/main/resources/assets/gregtech/worldgen/nether/sulfur_vein2.json
- src/main/resources/assets/gregtech/worldgen/nether/topaz_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/basaltic_mineral_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/cassiterite_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/chalcopyrite_vein1.json
- src/main/resources/assets/gregtech/worldgen/overworld/dolomite_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/kaolinite_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/kyanite_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/magnetite_vein2.json
- src/main/resources/assets/gregtech/worldgen/overworld/mica_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/oilsands_vein.json
- src/main/resources/assets/gregtech/worldgen/overworld/olivine_vein2.json
- src/main/resources/assets/gregtech/worldgen/overworld/pitchblende_vein3.json
- src/main/resources/assets/gregtech/worldgen/overworld/platinum_vein2.json
- src/main/resources/assets/gregtech/worldgen/overworld/topaz_vein.json
Updates some surface rock definitions to the newer surface rock format, and adds surface rocks to veins that did not have them before.
Let me know if there is any material that should be changed, as each surface rock yields a couple tiny dusts of material, and I don't know if that would mess with anything that is currently going on.
> Update and add surface rocks to veins

- src/main/java/gregicadditions/GAMaterials.java
- src/main/java/gregicadditions/item/GAMetaItem.java
- src/main/java/gregicadditions/item/GAMetaItems.java
- src/main/java/gregicadditions/recipes/RecipeHandler.java
- src/main/java/gregicadditions/recipes/categories/circuits/CircuitComponentRecipes.java
- src/main/java/gregicadditions/recipes/categories/circuits/CircuitRecipes.java
- src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
- src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
- src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
- src/main/resources/assets/gtadditions/lang/en_us.lang
+Added Exotic Circuits, Components, and relevant chains
+Added English localization for exotic circuits, components, and relevant chemicals
> Exotic Circuits

- build.properties
- src/main/java/gregicadditions/jei/AssemblyLineInfo.java
- src/main/java/gregicadditions/jei/GAMultiblockInfoCategory.java
- src/main/java/gregicadditions/jei/multi/simple/LargeCircuitAssemblyLineInfo.java
- src/main/java/gregicadditions/machines/multi/TileEntityFusionReactor.java
- src/main/java/gregicadditions/machines/multi/advance/TileEntityAdvFusionReactor.java
Fix Fusion Crash
Adds some tooltips to AL and CAL
Supersedes #562
> Updates GTCE in dev environment

- src/main/java/gregicadditions/recipes/chain/VariousChains.java
Simply adds a recipe for a material that had no recipe previously
> Add missing AlCl3 recipe

- src/main/java/gregicadditions/jei/FusionReactor4Info.java
- src/main/java/gregicadditions/recipes/chain/CosmicChain.java
- src/main/java/gregicadditions/recipes/chain/FusionElementsChain.java
Quickfix for initial EUt and adds tiers to the JEI preview, helpful for the freedom wrench
> Advanced Fusion Fixes

- src/main/java/gregicadditions/recipes/chain/FullereneChain.java
- src/main/java/gregicadditions/recipes/chain/SuperconductorsSMDChain.java
This PR fixes some invalid recipes on master.
> Fix Invalid Recipes

- src/main/java/gregicadditions/integrations/FECompat/GregicEnergyContainerWrapper.java
[This PR](https://github.com/GregTechCEu/GregTech/pull/294) but on gregicality
> fix energy acceptor

- src/main/java/gregicadditions/GAMaterials.java
- src/main/java/gregicadditions/recipes/chain/REEChain.java
Fixes the positive sulfuric acid and salt loops, as well as chlorine loss in the bromine chain.
> Fix Bromine Chain

- src/main/java/gregicadditions/integrations/exnihilocreatio/items/ExNihiloEnums.java
Why was this even a thing...
Closes #565 and Closes #616.
> fix double plates not having recipes

- src/main/java/gregicadditions/integrations/bees/alveary/TileGTAlveary.java
> fix alveary crash
